POST http://localhost:3000/api/corrector
content-type: application/json

{"content":"天色阴沉。\\n\\n苏玉成望着窗外，小小得眼睛里透露着不安得神色。\\n\\n“好像在下雨呢，”细凉得雨丝随风飘荡，滴落在苏玉成的脸上，冰冰的，“可是我今天忘记带伞了……”\\n\\n“苏玉成，苏玉成——”\\n\\n伴随着桌子的敲击声，苏玉成恍然从沉思中惊醒，匆忙着将目光从窗外收回，略带讨好地看着站在桌前的高大女人，低眉顺目。\\n\\n“林……林老师……”\\n\\n苏玉成有些窘迫， 10 岁的他在面对上课走神被抓的经验还略显不足，小嘴微张，支支吾吾的似乎想说些什么，但是很快就被打断了。\\n\\n“你家里有人找你，下午的课你可以不用上了，先出去吧。”看着眼前慌张的孩童，女子微微一笑，顺手扶了扶琥珀色大框塑料眼镜，没有多说些什么，只向着讲台上的正在授课的男人颔首示意，随后便离开了教室。"}